#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Ensure the entire project still compiles
blue=$(tput setaf 4)
normal=$(tput sgr0)
printf "%b" "${blue}Type checking... ${normal}"

npx eslint --no-error-on-unmatched-pattern "$(git diff --name-only origin/"$(git branch --show-current)".."$(git rev-parse --abbrev-ref)" HEAD)"
