#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

# Ensure the entire project still compiles
blue=$(tput setaf 4)
yellow=$(tput setaf 3)
green=$(tput setaf 2)
normal=$(tput sgr0)
printf "%b" "${blue}Linting & formatting${normal}${yellow} app${normal}..."
yarn app lint-staged -q
printf "%b" "${green}Success${normal}\n"

printf "%b" "${blue}Linting & formatting${normal}${yellow} sdk${normal}..."
yarn sdk lint-staged -q
printf "%b" "${green}Success${normal}\n"
