name: Preview Deploy

on:
  push:
    branches-ignore:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Install and Build
        run: yarn install --immutable && yarn build:preview
      - name: Run app tests
        run: yarn test
        working-directory: packages/app
      - name: Extract Branch Name and Commit Hash
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=hash;]$(echo ${GITHUB_SHA})"
        id: extract_vars
      - name: Publish to CloudFlare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_PLATFORM_CI_API_KEY }}
          command: pages publish ./packages/app/dist --project-name=platform-stability --branch=${{ steps.extract_vars.outputs.branch }} --commit-hash=${{ steps.extract_vars.outputs.hash }}
